# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: erl_playground.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='erl_playground.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14\x65rl_playground.proto\"\"\n\x0e\x63reate_session\x12\x10\n\x08username\x18\x01 \x02(\t\"!\n\x0eserver_message\x12\x0f\n\x07message\x18\x01 \x02(\t\"\x1f\n\x0cuser_request\x12\x0f\n\x07message\x18\x01 \x02(\t\"\xf0\x01\n\x03req\x12\x1c\n\x04type\x18\x01 \x02(\x0e\x32\x0e.req.type_enum\x12,\n\x13\x63reate_session_data\x18\x02 \x01(\x0b\x32\x0f.create_session\x12,\n\x13server_message_data\x18\x03 \x01(\x0b\x32\x0f.server_message\x12(\n\x11user_request_data\x18\x04 \x01(\x0b\x32\r.user_request\"E\n\ttype_enum\x12\x12\n\x0e\x63reate_session\x10\x01\x12\x12\n\x0eserver_message\x10\x02\x12\x10\n\x0cuser_request\x10\x03\"+\n\x08\x65nvelope\x12\x1f\n\x11uncompressed_data\x18\x02 \x02(\x0b\x32\x04.req'
)



_REQ_TYPE_ENUM = _descriptor.EnumDescriptor(
  name='type_enum',
  full_name='req.type_enum',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='create_session', index=0, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='server_message', index=1, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='user_request', index=2, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=300,
  serialized_end=369,
)
_sym_db.RegisterEnumDescriptor(_REQ_TYPE_ENUM)


_CREATE_SESSION = _descriptor.Descriptor(
  name='create_session',
  full_name='create_session',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='create_session.username', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=58,
)


_SERVER_MESSAGE = _descriptor.Descriptor(
  name='server_message',
  full_name='server_message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='server_message.message', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=93,
)


_USER_REQUEST = _descriptor.Descriptor(
  name='user_request',
  full_name='user_request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='user_request.message', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=126,
)


_REQ = _descriptor.Descriptor(
  name='req',
  full_name='req',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='req.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='create_session_data', full_name='req.create_session_data', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='server_message_data', full_name='req.server_message_data', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user_request_data', full_name='req.user_request_data', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _REQ_TYPE_ENUM,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=129,
  serialized_end=369,
)


_ENVELOPE = _descriptor.Descriptor(
  name='envelope',
  full_name='envelope',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uncompressed_data', full_name='envelope.uncompressed_data', index=0,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=371,
  serialized_end=414,
)

_REQ.fields_by_name['type'].enum_type = _REQ_TYPE_ENUM
_REQ.fields_by_name['create_session_data'].message_type = _CREATE_SESSION
_REQ.fields_by_name['server_message_data'].message_type = _SERVER_MESSAGE
_REQ.fields_by_name['user_request_data'].message_type = _USER_REQUEST
_REQ_TYPE_ENUM.containing_type = _REQ
_ENVELOPE.fields_by_name['uncompressed_data'].message_type = _REQ
DESCRIPTOR.message_types_by_name['create_session'] = _CREATE_SESSION
DESCRIPTOR.message_types_by_name['server_message'] = _SERVER_MESSAGE
DESCRIPTOR.message_types_by_name['user_request'] = _USER_REQUEST
DESCRIPTOR.message_types_by_name['req'] = _REQ
DESCRIPTOR.message_types_by_name['envelope'] = _ENVELOPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

create_session = _reflection.GeneratedProtocolMessageType('create_session', (_message.Message,), {
  'DESCRIPTOR' : _CREATE_SESSION,
  '__module__' : 'erl_playground_pb2'
  # @@protoc_insertion_point(class_scope:create_session)
  })
_sym_db.RegisterMessage(create_session)

server_message = _reflection.GeneratedProtocolMessageType('server_message', (_message.Message,), {
  'DESCRIPTOR' : _SERVER_MESSAGE,
  '__module__' : 'erl_playground_pb2'
  # @@protoc_insertion_point(class_scope:server_message)
  })
_sym_db.RegisterMessage(server_message)

user_request = _reflection.GeneratedProtocolMessageType('user_request', (_message.Message,), {
  'DESCRIPTOR' : _USER_REQUEST,
  '__module__' : 'erl_playground_pb2'
  # @@protoc_insertion_point(class_scope:user_request)
  })
_sym_db.RegisterMessage(user_request)

req = _reflection.GeneratedProtocolMessageType('req', (_message.Message,), {
  'DESCRIPTOR' : _REQ,
  '__module__' : 'erl_playground_pb2'
  # @@protoc_insertion_point(class_scope:req)
  })
_sym_db.RegisterMessage(req)

envelope = _reflection.GeneratedProtocolMessageType('envelope', (_message.Message,), {
  'DESCRIPTOR' : _ENVELOPE,
  '__module__' : 'erl_playground_pb2'
  # @@protoc_insertion_point(class_scope:envelope)
  })
_sym_db.RegisterMessage(envelope)


# @@protoc_insertion_point(module_scope)
